[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
reqwest = { version = "0.12", features = ["blocking", "cookies"] }
anyhow = "1.0"
csv = "1.3"
chrono = "0.4"

[profile.release]
opt-level = 2
lto = true
codegen-units = 1
